/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package reglash;

import java.util.ArrayList;

/**
 *
 * @author oracle
 */
public class ReglasFrame extends javax.swing.JFrame {

    /**
     * Creates new form ReglasFrame
     */
    ArrayList BC;
    ArrayList a1, a2, a3, a4, a5, a6, a7, a8, a9;
    Regla r1, r2, r3, r4, r5, r6, r7, r8, r9;
    String obj=null;

    public ReglasFrame() {
        initComponents();
        a1 = new ArrayList();
        a1.add("h8");
        a1.add("h6");
        a1.add("h5");
        r1 = new Regla("r1", a1, "h4");
        a2 = new ArrayList();
        a2.add("h6");
        a2.add("h3");
        r2 = new Regla("r2", a2, "h9");
        a3 = new ArrayList();
        a3.add("h7");
        a3.add("h4");
        r3 = new Regla("r3", a3, "h9");
        a4 = new ArrayList();
        a4.add("h8");
        r4 = new Regla("r4", a4, "h1");
        a5 = new ArrayList();
        a5.add("h6");
        r5 = new Regla("r5", a5, "h5");
        a6 = new ArrayList();
        a6.add("h9");
        a6.add("h1");
        r6 = new Regla("r6", a6, "h2");
        a7 = new ArrayList();
        a7.add("h7");
        r7 = new Regla("r7", a7, "h6");
        a8 = new ArrayList();
        a8.add("h1");
        a8.add("h7");
        r8 = new Regla("r8", a8, "h9");
        a9 = new ArrayList();
        a9.add("h1");
        a9.add("h8");
        r9 = new Regla("r9", a9, "h6");
        BC = new ArrayList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hecho1 = new javax.swing.JComboBox();
        hecho2 = new javax.swing.JComboBox();
        hecho3 = new javax.swing.JComboBox();
        objetivo = new javax.swing.JComboBox();
        evaluar1 = new javax.swing.JButton();
        evaluar2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        hecho1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "hecho", "h1", "h2", "h3", "h4", "h5", "h6", "h7", "h8", "h9" }));

        hecho2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "hecho", "h1", "h2", "h3", "h4", "h5", "h6", "h7", "h8", "h9" }));
        hecho2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hecho2ActionPerformed(evt);
            }
        });

        hecho3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "hecho", "h1", "h2", "h3", "h4", "h5", "h6", "h7", "h8", "h9" }));

        objetivo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "objetivo", "h1", "h2", "h3", "h4", "h5", "h6", "h7", "h8", "h9" }));

        evaluar1.setText("evaluar hacia adelante");
        evaluar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evaluar1ActionPerformed(evt);
            }
        });

        evaluar2.setText("evaluar hacia atras");
        evaluar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evaluar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(evaluar2)
                    .addComponent(evaluar1)
                    .addComponent(objetivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hecho3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hecho2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hecho1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(objetivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hecho1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hecho2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hecho3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(evaluar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(evaluar2)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hecho2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hecho2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hecho2ActionPerformed

    private void evaluar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evaluar1ActionPerformed
        // TODO add your handling code here:
        if (!hecho1.getSelectedItem().toString().equals("hecho")) {
            BC.add(hecho1.getSelectedItem().toString());
            System.out.println(hecho1.getSelectedItem().toString());
        }
        if (!hecho2.getSelectedItem().toString().equals("hecho")) {
            BC.add(hecho2.getSelectedItem().toString());
            System.out.println(hecho2.getSelectedItem().toString());
        }
        if (!hecho3.getSelectedItem().toString().equals("hecho")) {
            BC.add(hecho3.getSelectedItem().toString());
            System.out.println(hecho3.getSelectedItem().toString());
        }
        if (!objetivo.getSelectedItem().toString().equals("objetivo")) {
            obj = (objetivo.getSelectedItem().toString());
            System.out.println(objetivo.getSelectedItem().toString());
        }
        //hacia adelante
        String s;
        int i = 0;
        int b = 0;
        s = (String) BC.get(i);
        while (true) {
            if (i > 9) {
                i = 0;
            }
            System.out.println(i + s);
            if(s.equals(obj) || BC.size()==9){
                return;
            }
            ArrayList reglas = new ArrayList();
            if (a1.contains(s)) {
                reglas.add(r1);
                System.out.println(" 1");
            }
            if (a2.contains(s)) {
                reglas.add(r2);
                System.out.println(" 2");
            }
            if (a3.contains(s)) {
                reglas.add(r3);
                System.out.println(" 3");
            }
            if (a4.contains(s)) {
                reglas.add(r4);
                System.out.println(" 4");
            }
            if (a5.contains(s)) {
                reglas.add(r5);
                System.out.println(" 5");
            }
            if (a6.contains(s)) {
                reglas.add(r6);
                System.out.println(" 6");
            }
            if (a7.contains(s)) {
                reglas.add(r7);
                System.out.println(" 7");
            }
            if (a8.contains(s)) {
                reglas.add(r8);
                System.out.println(" 8");
            }
            if (a9.contains(s)) {
                reglas.add(r9);
                System.out.println(" 9");
            }
            Regla r = null;
            for (int reg = 0; reg < reglas.size(); reg++) {
                for (int bc = 0; bc < BC.size(); bc++) {
                    if (((Regla) reglas.get(reg)).getCondiciones().contains(BC.get(bc))) {
                        if (r == null) {
                            r = ((Regla) reglas.get(reg));
                        } else {
                            if (r.getCondiciones().size() > ((Regla) reglas.get(reg)).getCondiciones().size()) {
                                r = ((Regla) reglas.get(reg));
                            }
                        }
                    }
                }
            }
            if (r != null) {
                if (r.getCondiciones().size() == 1) {
                    BC.add(r.getConclusion());
                } else {
                    if (r.getCondiciones().size() == 2) {
                        if (((String) r.getCondiciones().get(0)).equals(s)) {
                            if (BC.contains(r.getCondiciones().get(1))) {
                                BC.add(r.getConclusion());
                            } else {
                                s = (String) r.getCondiciones().get(1);
                                b = 1;
                            }
                        } else {
                            if (BC.contains(r.getCondiciones().get(0))) {
                                BC.add(r.getConclusion());
                            } else {
                                s = (String) r.getCondiciones().get(0);
                                b = 1;
                            }
                        }
                    }
                }
            }
            for(int k=0;k<BC.size();k++){
                System.out.println(obj+BC.get(k));
            }
            if (BC.contains(obj) || BC.size()==9) {
                System.out.println("llega");
                return;
            }
            if (b == 0 && i<BC.size()) {
                s = (String) BC.get(i);
            } else {
                b = 0;
            }
            i++;
        }
    }//GEN-LAST:event_evaluar1ActionPerformed

    private void evaluar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evaluar2ActionPerformed
        // TODO add your handling code here:
        if (!hecho1.getSelectedItem().toString().equals("hecho")) {
            BC.add(hecho1.getSelectedItem().toString());
            System.out.println(hecho1.getSelectedItem().toString());
        }
        if (!hecho2.getSelectedItem().toString().equals("hecho")) {
            BC.add(hecho2.getSelectedItem().toString());
            System.out.println(hecho2.getSelectedItem().toString());
        }
        if (!hecho3.getSelectedItem().toString().equals("hecho")) {
            BC.add(hecho3.getSelectedItem().toString());
            System.out.println(hecho3.getSelectedItem().toString());
        }
        if (!objetivo.getSelectedItem().toString().equals("objetivo")) {
            obj = (objetivo.getSelectedItem().toString());
            System.out.println(objetivo.getSelectedItem().toString());
        }
        
    }//GEN-LAST:event_evaluar2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReglasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReglasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReglasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReglasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReglasFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton evaluar1;
    private javax.swing.JButton evaluar2;
    private javax.swing.JComboBox hecho1;
    private javax.swing.JComboBox hecho2;
    private javax.swing.JComboBox hecho3;
    private javax.swing.JComboBox objetivo;
    // End of variables declaration//GEN-END:variables
}
