package algoritmoheuristico;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

public class Ventana extends javax.swing.JFrame {
    int[][] matriz;
    int[] conexion;
    Grafos grafos;
    int bandera=1;
    int con = 1;
    int b=1;
    public Ventana() {
        initComponents();
        this.buttonGroup1.add(this.jRadioButton1);
        this.buttonGroup1.add(this.jRadioButton2);
        grafos = new Grafos();        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jButton1.setText("VER MATRIZ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setEnabled(false);
        jScrollPane1.setViewportView(jTextArea1);

        jButton2.setText("VER GRAFO");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel1.setOpaque(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabel1.setText("VALOR:");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setOpaque(true);

        jLabel3.setBackground(new java.awt.Color(51, 204, 0));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ALGORITMO HEURÍSTICO");
        jLabel3.setOpaque(true);

        jRadioButton1.setText("Maximizar");

        jRadioButton2.setText("Minimizar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButton2))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(this.jRadioButton1.isSelected()==false && this.jRadioButton2.isSelected()==false){
            JOptionPane.showMessageDialog(null, "Seleciones Maximizar o Minimizar");
        }else{
            if(bandera==1){
            this.matriz = grafos.getMatriz(1);
            this.conexion = grafos.getConexion(1,this.getOpcion());
            bandera++;
            }else if(bandera==2){
                this.matriz = grafos.getMatriz(2);
                this.conexion = grafos.getConexion(2,this.getOpcion());
                bandera++;
            }else if(bandera==3){
                this.matriz = grafos.getMatriz(3);
                this.conexion = grafos.getConexion(3,this.getOpcion());
                bandera=1;
            }
            jTextArea1.setText(null);
            verMatriz();
        }        
    }//GEN-LAST:event_jButton1ActionPerformed

    public int getOpcion(){
        if(jRadioButton1.isSelected()==true){   //MAXIMIZAR
            return 1;
        }else{
            return 0;                           //MINIMIZAR 
        }        
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
            jPanel1.getGraphics().clearRect(0, 0, 300, 300);
            this.b=1;
            jLabel2.setText(null);

            hacerLinea(this.jPanel1.getGraphics(),9*(300/22),3*(300/22),13*(300/22),3*(300/22));
            hacerLinea(this.jPanel1.getGraphics(),13*(300/22),3*(300/22),17*(300/22),6*(300/22));
            hacerLinea(this.jPanel1.getGraphics(),17*(300/22),6*(300/22),19*(300/22),11*(300/22));
            hacerLinea(this.jPanel1.getGraphics(),19*(300/22),11*(300/22),17*(300/22),16*(300/22));
            hacerLinea(this.jPanel1.getGraphics(),17*(300/22),16*(300/22),13*(300/22),19*(300/22));
            hacerLinea(this.jPanel1.getGraphics(),13*(300/22),19*(300/22),9*(300/22),19*(300/22));
            hacerLinea(this.jPanel1.getGraphics(),13*(300/22),19*(300/22),9*(300/22),19*(300/22));
            hacerLinea(this.jPanel1.getGraphics(),9*(300/22),19*(300/22),5*(300/22),16*(300/22));
            hacerLinea(this.jPanel1.getGraphics(),5*(300/22),16*(300/22),3*(300/22),11*(300/22));
            hacerLinea(this.jPanel1.getGraphics(),3*(300/22),11*(300/22),5*(300/22),6*(300/22));
            hacerLinea(this.jPanel1.getGraphics(),5*(300/22),6*(300/22),9*(300/22),3*(300/22));        

            hacerCirculo(this.jPanel1.getGraphics(),8*(300/22),2*(300/22),25);
            hacerCirculo(this.jPanel1.getGraphics(),12*(300/22),2*(300/22),25);
            hacerCirculo(this.jPanel1.getGraphics(),16*(300/22),5*(300/22),25);
            hacerCirculo(this.jPanel1.getGraphics(),18*(300/22),10*(300/22),25);
            hacerCirculo(this.jPanel1.getGraphics(),16*(300/22),15*(300/22),25);
            hacerCirculo(this.jPanel1.getGraphics(),12*(300/22),18*(300/22),25);
            hacerCirculo(this.jPanel1.getGraphics(),8*(300/22),18*(300/22),25);
            hacerCirculo(this.jPanel1.getGraphics(),4*(300/22),15*(300/22),25);
            hacerCirculo(this.jPanel1.getGraphics(),2*(300/22),10*(300/22),25);
            hacerCirculo(this.jPanel1.getGraphics(),4*(300/22),5*(300/22),25);

            hacerEtiqueta(this.jPanel1.getGraphics(), (int) (8.5*(300/22)),3*(300/22),Integer.toString(this.conexion[0]));
            hacerEtiqueta(this.jPanel1.getGraphics(),11*(300/22),3*(300/22),Integer.toString(this.conexion[1]));
            hacerEtiqueta(this.jPanel1.getGraphics(), (int) (12.5*(300/22)),3*(300/22),Integer.toString(this.conexion[2]));
            hacerEtiqueta(this.jPanel1.getGraphics(),15*(300/22),5*(300/22),Integer.toString(this.conexion[3]));
            hacerEtiqueta(this.jPanel1.getGraphics(), (int) (16.5*(300/22)), (int) (6.5*(300/22)),Integer.toString(this.conexion[4]));
            hacerEtiqueta(this.jPanel1.getGraphics(),19*(300/22),8*(300/22),Integer.toString(this.conexion[5]));
            hacerEtiqueta(this.jPanel1.getGraphics(), (int) (18.5*(300/22)), (int) (11*(300/22)),Integer.toString(this.conexion[6]));
            hacerEtiqueta(this.jPanel1.getGraphics(),19*(300/22),14*(300/22),Integer.toString(this.conexion[7]));
            hacerEtiqueta(this.jPanel1.getGraphics(), (int) (16.5*(300/22)), (int) (16*(300/22)),Integer.toString(this.conexion[8]));
            hacerEtiqueta(this.jPanel1.getGraphics(),15*(300/22),18*(300/22),Integer.toString(this.conexion[9]));        
            hacerEtiqueta(this.jPanel1.getGraphics(), (int) (12.5*(300/22)), (int) (19*(300/22)),Integer.toString(this.conexion[10]));
            hacerEtiqueta(this.jPanel1.getGraphics(),11*(300/22),19*(300/22),Integer.toString(this.conexion[11]));
            hacerEtiqueta(this.jPanel1.getGraphics(), (int) (9*(300/22)), (int) (19*(300/22)),Integer.toString(this.conexion[12]));
            hacerEtiqueta(this.jPanel1.getGraphics(),6*(300/22),18*(300/22),Integer.toString(this.conexion[13]));
            hacerEtiqueta(this.jPanel1.getGraphics(), (int) (5*(300/22)), (int) (16*(300/22)),Integer.toString(this.conexion[14]));
            hacerEtiqueta(this.jPanel1.getGraphics(),3*(300/22),14*(300/22),Integer.toString(this.conexion[15]));
            hacerEtiqueta(this.jPanel1.getGraphics(), (int) (2.5*(300/22)), (int) (11*(300/22)),Integer.toString(this.conexion[16]));
            hacerEtiqueta(this.jPanel1.getGraphics(),3*(300/22),8*(300/22),Integer.toString(this.conexion[17]));
            hacerEtiqueta(this.jPanel1.getGraphics(), (int) (4.5*(300/22)), (int) (6*(300/22)),Integer.toString(this.conexion[18]));
            hacerEtiqueta(this.jPanel1.getGraphics(),6*(300/22),4*(300/22),Integer.toString(this.conexion[19]));                
            calcularValorMinimo();
        }catch(NullPointerException e){
            JOptionPane.showMessageDialog( null, "NO HAY MATRIZ DE CONEXIÓN");
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed
    public void calcularValorMinimo(){
        int suma =0;
        for(int i=1;i<20;i=i+2){
            suma = suma + this.conexion[i];
        }
        jLabel2.setText(Integer.toString(suma));
    }
    public void hacerLinea(Graphics g, int x, int y, int x1, int y1){
        Graphics2D g2d = (Graphics2D) g;        
        g2d.setStroke(new BasicStroke(3));
        g2d.setColor(Color.red);
        g2d.drawLine(x, y, x1, y1);
    }
    public void hacerEtiqueta(Graphics g, int x, int y,String s){
        Font texto = new Font("Serief",Font.BOLD,14);
        Graphics2D g2d = (Graphics2D) g;
        g2d.setFont(texto);
        if(this.con == 1){
            g2d.setColor(Color.ORANGE);
            this.con++;            
        }else{
            g2d.setColor(Color.BLACK);
            this.con--;
        }        
        g2d.drawString(s, x, y);
    }
    public void hacerCirculo(Graphics g, int x, int y,int a){
        if(this.b==1){
            g.setColor(Color.YELLOW); 
            this.b++;
        }else{
            g.setColor(Color.BLUE);
        }
        
        g.fillOval(x, y, a, a);               
    }
    public void verMatriz(){
        for(int i=0;i<10;i++){
            for(int j=0;j<10;j++){
                if(this.matriz[i][j]<10){
                    jTextArea1.append(matriz[i][j]+"   ");
                }else{
                    jTextArea1.append(matriz[i][j]+" ");
                }
                
            }
            jTextArea1.append("\n");
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException{
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        UIManager.setLookAndFeel("com.sun.java.swing.plaf.motif.MotifLookAndFeel");

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
