/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectsisexp;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Fer
 */
public class Ventana extends javax.swing.JFrame {

    public static Ventana vnt = new Ventana();
    
    public void setJTxtArea2(String str){
        jTextArea2.setText(str);
    }
    

    
    public void setJTxtArea5(String str){
        jTextArea5.setText(str);
    }
    
    public String getJtextField1(){
        
       String tex = (String) jTextField1.getText();
       tex = tex.toUpperCase();
       jTextField1.setText("");
        return tex;
    }
    
    
    public Ventana() {
        
        initComponents();
      //  ReportePDF reporte = new ReportePDF();
       // jTextArea2.setEditable(false);
        //jTextArea4.setEditable(false);
        //jTextArea5.setEditable(false);
        //jTextArea4.setVisible(true);
        jTextArea5.setVisible(true);
        this.setLocationRelativeTo(null);
        setSize(583, 485);
        
//        File archivo = new File ("cajero.jpg");
//        File archivo2 = new File ("ejecutivo.png");
//        File archivo3 = new File ("gerente.jpg");
//        File archivo4 = new File ("fondo.jpg");
        
        
        
        BufferedImage imgsel2;
        //Image img = null;
        //ImageIcon icon = new ImageIcon(img);
        //Image imgEscalada = icon.getImage().getScaledInstance(jLabel5.getWidth(),
         //       jLabel5.getHeight(), Image.SCALE_SMOOTH);
//        Icon iconoEscalado = new ImageIcon(imgEscalada);
//        jLabel5.setIcon(iconoEscalado);
//        icon = new ImageIcon(img);
//        imgEscalada = icon.getImage().getScaledInstance(jLabel7.getWidth(),
//                jLabel7.getHeight(), Image.SCALE_SMOOTH);
//        iconoEscalado = new ImageIcon(imgEscalada);
//        jLabel7.setIcon(iconoEscalado);
//        icon = new ImageIcon(img);
//        imgEscalada = icon.getImage().getScaledInstance(jLabel6.getWidth(),
//                jLabel6.getHeight(), Image.SCALE_SMOOTH);
//        iconoEscalado = new ImageIcon(imgEscalada);
//        jLabel6.setIcon(iconoEscalado);
//        icon = new ImageIcon(img);
//        imgEscalada = icon.getImage().getScaledInstance(jLabel9.getWidth(),
//                jLabel9.getHeight(), Image.SCALE_SMOOTH);
//        iconoEscalado = new ImageIcon(imgEscalada);
//        jLabel9.setIcon(iconoEscalado);
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("/root/NetBeansProjects/ProyectSisExp/ProyectSisExp/estudio.jpg")); // NOI18N
        jLabel1.setText("Estudio fotográfico  Don Davo");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, -20, 520, 240);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Mostrador");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(390, 220, 100, 23);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Entregas");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 220, 90, 23);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 140, 150, 115);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(630, 85, 150, 115);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(340, 150, 150, 115);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(300, 280, 246, 138);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(260, 430, 151, 26);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 153, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Cliente:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(190, 430, 53, 20);

        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jScrollPane5.setViewportView(jTextArea5);

        getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(20, 280, 246, 138);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel9);
        jLabel9.setBounds(490, 130, 360, 350);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
     
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Ventana().setVisible(true);
                vnt.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
